### ISSUE TITLE
AttributeError: 'BF16_Optimizer' object has no attribute 'cur_scale'

### ISSUE THREAD

**Issue by xin0623** [OpenGVLab/InternVideo#121]
The error occurred when I tried to fine-tune in single_modality

Traceback (most recent call last):
  File "run_finetuning.py", line 719, in <module>
    main(opts, ds_init)
  File "run_finetuning.py", line 636, in main
    train_stats = train_one_epoch(
  File "/mnt2/xiayingxin/InternVideo/InternVideo2/single_modality/engines/engine_for_finetuning.py", line 92, in train_one_epoch
    loss_scale_value = get_loss_scale_for_deepspeed(model)
  File "/mnt2/xiayingxin/InternVideo/InternVideo2/single_modality/engines/engine_for_finetuning.py", line 22, in get_loss_scale_for_deepspeed
    return optimizer.loss_scale if hasattr(optimizer, "loss_scale") else optimizer.cur_scale
AttributeError: 'BF16_Optimizer' object has no attribute 'cur_scale'

**Comment by Andy1621** [comment]
Can you provide your DeepSpeed version?

**Comment by xin0623** [comment]
deepspeed==0.10.1
