### ISSUE TITLE
Errors loading InternVid dataset

### ISSUE THREAD

**Issue by adeobootpin** [OpenGVLab/InternVideo#72]
After running the following as suggested in the Hugging Face dataset card:

_from datasets import load_dataset
dataset = load_dataset("OpenGVLab/InternVid")_

I get the errors below. How do I fix this? Thanks.

Downloading readme: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.42k/2.42k [00:00<00:00, 1.69MB/s]
Downloading data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.32G/2.32G [00:55<00:00, 41.7MB/s]
Downloading data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.89G/3.89G [01:34<00:00, 41.0MB/s]
Downloading data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.69G/1.69G [00:41<00:00, 40.9MB/s]
Generating FLT split: 10647458 examples [00:06, 1742162.92 examples/s]
Generating AES split: 0 examples [00:00, ? examples/s]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 1989, in _prepare_split_single
    writer.write_table(table)
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_writer.py", line 574, in write_table
    pa_table = table_cast(pa_table, self._schema)
  File "/opt/conda/lib/python3.10/site-packages/datasets/table.py", line 2322, in table_cast
    return cast_table_to_schema(table, schema)
  File "/opt/conda/lib/python3.10/site-packages/datasets/table.py", line 2276, in cast_table_to_schema
    raise CastError(
datasets.table.CastError: Couldn't cast
YoutubeID: string
Start_timestamp: string
End_timestamp: string
Caption: string
CLIP_Score: double
Aesthetic_Score: double
to
{'YoutubeID': Value(dtype='string', id=None), 'Start_timestamp': Value(dtype='string', id=None), 'End_timestamp': Value(dtype='string', id=None), 'Caption': Value(dtype='string', id=None), 'Aesthetic_Score': Value(dtype='float64', id=None), 'UMT_Score': Value(dtype='float64', id=None)}
because column names don't match

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//vidd.py", line 15, in <module>
    dataset = load_dataset("OpenGVLab/InternVid")
  File "/opt/conda/lib/python3.10/site-packages/datasets/load.py", line 2549, in load_dataset
    builder_instance.download_and_prepare(
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 1005, in download_and_prepare
    self._download_and_prepare(
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 1100, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 1860, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 1991, in _prepare_split_single
    raise DatasetGenerationCastError.from_cast_error(
datasets.exceptions.DatasetGenerationCastError: An error occurred while generating the dataset

All the data files must have the same columns, but at some point there are 1 new columns (CLIP_Score) and 1 missing columns (UMT_Score).

This happened while the json dataset builder was generating data using

hf://datasets/OpenGVLab/InternVid/InternVid-18M-aes.jsonl (at revision 0a37cb751c13b94965a1ec88ac16ed3c595d1ea6)

Please either edit the data files to have matching columns, or separate them into different configurations (see docs at https://hf.co/docs/hub/datasets-manual-configuration#multiple-configurations)

**Comment by yinanhe** [comment]
This issue is because the fields of different sets are different. We have already updated the Multiple Configurations. Please try again.

**Comment by adeobootpin** [comment]
Thanks!
It works now.
